### ISSUE TITLE
Error 400 Bad Request

### ISSUE THREAD

**Issue by DevFil** [farhaan444/Telegram-Bot#17]
Hello, congratulations on your project, really good!
I have a problem, when i search a Flight, the search fail and i get this error: 
`aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tequila.kiwi.com/v2/flights_multi'). `
I tried to make the request via curl and the response is: 
`{"status": "Bad Request", "error": "unknown partner provided - if you would like to cooperate with Kiwi.com, please register at tequila.kiwi.com"}.`
Do you know how i can fix it?
Thank You

**Comment by farhaan444** [comment]
Hi and Thank you!

with your first error, this is a bug in the code when searching for a multi-city flight search. you can only search/call api when you have more than two flight requests. I have pushed a new pull request now and fixed this bug. 

The second error you getting via curl is because you may have not added your api key in your header.

**Comment by DevFil** [comment]
Thank you for the reply!
